Question 1: What is a Support Vector Machine (SVM), and how does it work?
Ans:- Support Vector Machine (SVM)

A Support Vector Machine (SVM) is a supervised learning algorithm used for classification and regression tasks. It's a powerful and popular algorithm in machine learning.

How SVM Works

* Objective: SVM aims to find the best hyperplane (decision boundary) that separates the data into different classes.
* Hyperplane: A hyperplane is a line (in 2D) or a plane (in 3D) that separates the data.
* Support Vectors: The data points closest to the hyperplane are called support vectors. These points are crucial in defining the hyperplane.
* Margin: The distance between the hyperplane and the support vectors is called the margin. SVM aims to maximize this margin.
* Kernel Trick: SVM uses the kernel trick to transform the data into a higher-dimensional space, making it easier to find a hyperplane.

Key Characteristics

- Robust to noise: SVM is robust to noise and outliers.
- Effective in high-dimensional spaces: SVM works well in high-dimensional spaces.
- Memory-intensive: SVM can be memory-intensive for large datasets.

Types of SVM

- Linear SVM: Used for linearly separable data.
- Non-Linear SVM: Used for non-linearly separable data (uses kernel trick).

Common Kernels

- Linear Kernel: Used for linearly separable data.
- Polynomial Kernel: Used for polynomial relationships.
- Radial Basis Function (RBF) Kernel: Used for non-linear relationships.

SVM is widely used in various applications, including image classification, text classification, and bioinformatics.

Question 2: Explain the difference between Hard Margin and Soft Margin SVM.
Ans:- Hard Margin SVM vs Soft Margin SVM

Hard Margin SVM and Soft Margin SVM are two types of SVM approaches used for classification tasks.

Hard Margin SVM

- Assumes linearly separable data: Hard Margin SVM assumes that the data is linearly separable, meaning it can be separated by a hyperplane without any errors.
- No misclassifications allowed: Hard Margin SVM doesn't allow any misclassifications, meaning all data points must be on the correct side of the hyperplane.
- Sensitive to noise and outliers: Hard Margin SVM is sensitive to noise and outliers, as a single misclassified point can significantly affect the hyperplane.
- Prone to overfitting: Hard Margin SVM can be prone to overfitting, especially when the data is noisy or has outliers.

Soft Margin SVM

- Allows misclassifications: Soft Margin SVM allows some misclassifications, meaning some data points can be on the wrong side of the hyperplane.
- Introduces slack variables: Soft Margin SVM introduces slack variables to relax the constraints, allowing some data points to be misclassified.
- More robust to noise and outliers: Soft Margin SVM is more robust to noise and outliers, as it can tolerate some misclassifications.
- Less prone to overfitting: Soft Margin SVM is less prone to overfitting, as it allows some misclassifications and is more robust to noise.

Key differences

- Handling misclassifications: Hard Margin SVM doesn't allow misclassifications, while Soft Margin SVM allows some misclassifications.
- Robustness to noise: Soft Margin SVM is more robust to noise and outliers compared to Hard Margin SVM.
- Overfitting: Soft Margin SVM is less prone to overfitting compared to Hard Margin SVM.

In practice, Soft Margin SVM is more commonly used, as it can handle noisy and non-linearly separable data.

Question 3: What is the Kernel Trick in SVM? Give one example of a kernel and
explain its use case.
Ans:- Kernel Trick in SVM

The Kernel Trick is a technique used in SVM to transform the original data into a higher-dimensional space, making it easier to find a hyperplane that separates the data. This is done without explicitly computing the transformation, which can be computationally expensive.

How the Kernel Trick works

* Compute dot products: Instead of transforming the data, SVM computes the dot product of the data points in the original space.
* Use a kernel function: A kernel function is used to compute the dot product in the higher-dimensional space.
* Replace dot products: The kernel function replaces the dot product computation, allowing SVM to work in the higher-dimensional space without explicit transformation.

Example: Radial Basis Function (RBF) Kernel

The RBF kernel is a popular kernel used in SVM. It's defined as:

K(x, y) = exp(-γ ||x - y||^2)

where x and y are data points, γ is a hyperparameter, and ||.|| is the Euclidean norm.

Use case: Non-linearly separable data

The RBF kernel is useful when the data is non-linearly separable. It maps the data into a higher-dimensional space, making it easier to find a hyperplane that separates the data.

For example, consider a dataset with two features (x1, x2) and two classes. The data is non-linearly separable in the original space, but the RBF kernel can transform it into a higher-dimensional space where it's linearly separable.

The RBF kernel is widely used in image classification, text classification, and other applications where the data is non-linearly separable.

Question 4: What is a Naïve Bayes Classifier, and why is it called “naïve”?
Ans:- Naïve Bayes Classifier

A Naïve Bayes Classifier is a probabilistic machine learning model used for classification tasks. It's based on Bayes' theorem and assumes independence between features, which is why it's called "naïve".

How Naïve Bayes works

* Bayes' theorem: The classifier uses Bayes' theorem to update the probability of a class given the features.
* Independence assumption: The classifier assumes that the features are independent, meaning the presence or absence of one feature doesn't affect the others.
* Calculate probabilities: The classifier calculates the probability of each class given the features and chooses the class with the highest probability.

Why is it called "naïve"?

It's called "naïve" because of the independence assumption, which is often unrealistic in real-world data. In most cases, features are not independent, and there are correlations between them. Despite this, Naïve Bayes often performs surprisingly well, especially with large datasets.

Key characteristics

- Simple and efficient: Naïve Bayes is a simple and efficient algorithm, making it suitable for large datasets.
- Probabilistic: The classifier provides probabilities for each class, allowing for uncertainty estimation.
- Handles high-dimensional data: Naïve Bayes can handle high-dimensional data, making it suitable for text classification and other applications.

Common applications

- Text classification: Naïve Bayes is widely used in text classification tasks, such as spam filtering and sentiment analysis.
- Image classification: It's also used in image classification tasks, such as object detection and image categorization.

Question 5: Describe the Gaussian, Multinomial, and Bernoulli Naïve Bayes variants.When would you use each one?
Ans:- Naïve Bayes Variants

There are three main variants of Naïve Bayes classifiers, each suited for different types of data:

* Gaussian Naïve Bayes- Assumes continuous features: Gaussian Naïve Bayes assumes that the features are continuous and follow a Gaussian (normal) distribution.
- Use case: Use Gaussian Naïve Bayes when dealing with continuous features, such as image pixel values or sensor readings.

* Multinomial Naïve Bayes- Assumes count-based features: Multinomial Naïve Bayes assumes that the features are count-based, such as word frequencies in text classification.
- Use case: Use Multinomial Naïve Bayes when dealing with text classification, sentiment analysis, or other count-based features.

* Bernoulli Naïve Bayes- Assumes binary features: Bernoulli Naïve Bayes assumes that the features are binary (0/1, yes/no, etc.).
- Use case: Use Bernoulli Naïve Bayes when dealing with binary features, such as presence/absence of words in text or binary sensor data.

Choosing the right variant

- Check feature type: Choose the variant based on the type of features you're working with (continuous, count-based, or binary).
- Data distribution: Consider the distribution of your data and choose the variant that best matches it.

Here's a rough guide:

| Feature Type | Naïve Bayes Variant |
| ------------ | -------------------- |
| Continuous | Gaussian |
| Count-based | Multinomial |
| Binary | Bernoulli |


Write a Python program to:
● Load the Iris dataset
● Train an SVM Classifier with a linear kernel
● Print the model's accuracy and support vectors.


In [1]:
from sklearn import datasets
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Load the Iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train an SVM Classifier with a linear kernel
svm = SVC(kernel='linear')
svm.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = svm.predict(X_test)

# Print the model's accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")

# Print the support vectors
print("Support Vectors:")
print(svm.support_vectors_)

# Print the number of support vectors
print(f"Number of Support Vectors: {len(svm.support_vectors_)}")




Model Accuracy: 1.00
Support Vectors:
[[4.8 3.4 1.9 0.2]
 [5.1 3.3 1.7 0.5]
 [4.5 2.3 1.3 0.3]
 [5.6 3.  4.5 1.5]
 [5.4 3.  4.5 1.5]
 [6.7 3.  5.  1.7]
 [5.9 3.2 4.8 1.8]
 [5.1 2.5 3.  1.1]
 [6.  2.7 5.1 1.6]
 [6.3 2.5 4.9 1.5]
 [6.1 2.9 4.7 1.4]
 [6.5 2.8 4.6 1.5]
 [6.9 3.1 4.9 1.5]
 [6.3 2.3 4.4 1.3]
 [6.3 2.5 5.  1.9]
 [6.3 2.8 5.1 1.5]
 [6.3 2.7 4.9 1.8]
 [6.  3.  4.8 1.8]
 [6.  2.2 5.  1.5]
 [6.2 2.8 4.8 1.8]
 [6.5 3.  5.2 2. ]
 [7.2 3.  5.8 1.6]
 [5.6 2.8 4.9 2. ]
 [5.9 3.  5.1 1.8]
 [4.9 2.5 4.5 1.7]]
Number of Support Vectors: 25


Question 7: Write a Python program to:
● Load the Breast Cancer dataset
● Train a Gaussian Naïve Bayes model
● Print its classification report including precision, recall, and F1-score.

In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report

# Load the Breast Cancer dataset
breast_cancer = datasets.load_breast_cancer()
X = breast_cancer.data
y = breast_cancer.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Gaussian Naïve Bayes model
gnb = GaussianNB()
gnb.fit(X_train, y_train)

# Make predictions on the testing set
y_pred = gnb.predict(X_test)

# Print the classification report
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=breast_cancer.target_names))


Classification Report:
              precision    recall  f1-score   support

   malignant       1.00      0.93      0.96        43
      benign       0.96      1.00      0.98        71

    accuracy                           0.97       114
   macro avg       0.98      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



Question 8: Write a Python program to:
● Train an SVM Classifier on the Wine dataset using GridSearchCV to find the best
C and gamma.
● Print the best hyperparameters and accuracy.

In [3]:
from sklearn import datasets
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# Load the Wine dataset
wine = datasets.load_wine()
X = wine.data
y = wine.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define hyperparameter grid for GridSearchCV
param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [0.01, 0.1, 1, 10],
    'kernel': ['rbf']
}

# Perform GridSearchCV to find the best hyperparameters
grid_search = GridSearchCV(SVC(), param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Get the best hyperparameters and train an SVM Classifier
best_svm = grid_search.best_estimator_
best_params = grid_search.best_params_
y_pred = best_svm.predict(X_test)

# Print the best hyperparameters and accuracy
print(f"Best Hyperparameters: {best_params}")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")




Best Hyperparameters: {'C': 10, 'gamma': 0.01, 'kernel': 'rbf'}
Accuracy: 0.67


Question 9: Write a Python program to:
● Train a Naïve Bayes Classifier on a synthetic text dataset (e.g. using
sklearn.datasets.fetch_20newsgroups).
● Print the model's ROC-AUC score for its predictions.

In [4]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
import numpy as np

# Load the 20 Newsgroups dataset (binary classification, e.g., 'alt.atheism' vs 'soc.religion.christian')
categories = ['alt.atheism', 'soc.religion.christian']
newsgroups = fetch_20newsgroups(categories=categories)
X = newsgroups.data
y = newsgroups.target

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Vectorize text data using TF-IDF
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Train a Multinomial Naïve Bayes Classifier
mnb = MultinomialNB()
mnb.fit(X_train_tfidf, y_train)

# Make predictions on the testing set
y_pred_proba = mnb.predict_proba(X_test_tfidf)[:, 1]

# Print the ROC-AUC score
roc_auc = roc_auc_score(y_test, y_pred_proba)
print(f"ROC-AUC Score: {roc_auc:.2f}")




ROC-AUC Score: 1.00


Question 10: Imagine you’re working as a data scientist for a company that handles
email communications.
Your task is to automatically classify emails as Spam or Not Spam. The emails may
contain:
● Text with diverse vocabulary
● Potential class imbalance (far more legitimate emails than spam)
● Some incomplete or missing data
Explain the approach you would take to:
● Preprocess the data (e.g. text vectorization, handling missing data)
● Choose and justify an appropriate model (SVM vs. Naïve Bayes)
● Address class imbalance
● Evaluate the performance of your solution with suitable metrics
And explain the business impact of your solution

 Ans:-  Approach to Email Classification

Preprocessing the Data1. Text Vectorization: Use TF-IDF (Term Frequency-Inverse Document Frequency) to convert text data into numerical vectors. This will help capture the importance of words in the email content.
* Handling Missing Data: Use imputation techniques like replacing missing values with mean/median or using a K-Nearest Neighbors (KNN) imputer. Alternatively, consider using models that can handle missing data, like decision trees or random forests.
* Data Cleaning: Remove stop words, punctuation, and special characters. Apply stemming or lemmatization to reduce words to their base form.

Model Selection1. Naïve Bayes: A good starting point for text classification tasks, especially with TF-IDF vectorization. It's simple, efficient, and often performs well.
* SVM: A strong contender, especially with class imbalance. However, it may require more tuning and computational resources.

Given the text nature of the data and potential class imbalance, I would start with Multinomial Naïve Bayes and compare its performance with SVM.

Addressing Class Imbalance1. Class Weighting: Use class weighting techniques, like assigning higher weights to the minority class (Spam), to help the model focus on it.
* Oversampling/Undersampling: Use techniques like SMOTE (Synthetic Minority Over-sampling Technique) or random undersampling to balance the classes.
* Anomaly Detection: Consider framing the problem as anomaly detection, where Spam emails are treated as anomalies.

Evaluation Metrics1. Precision: Important to ensure that legitimate emails aren't incorrectly classified as Spam.
* Recall: Crucial to catch as many Spam emails as possible.
* F1-score: A balanced measure of precision and recall.
* AUC-ROC: Evaluate the model's ability to distinguish between classes.

Business Impact1. Improved Email Experience: Accurate Spam filtering will improve the overall email experience for users, reducing clutter and increasing productivity.
* Reduced False Positives: Minimizing false positives (legitimate emails marked as Spam) will ensure important emails aren't missed.
* Increased Security: Effective Spam filtering will reduce phishing and malware risks, protecting users and the company.
* Cost Savings: Automating Spam filtering will reduce manual effort and costs associated with email management.





In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, f1_score
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

# Load email data
# Replace with your actual email data and labels
emails = [
    "This is a legitimate email about a meeting.",
    "Buy now and get a free gift! Limited time offer.",
    "Meeting scheduled for tomorrow at 10 AM.",
    "Click here to claim your prize!",
    "Important update regarding your account.",
    "Spam email with malicious link.",
    "Just a friendly reminder.",
    "Earn money fast!",
    "Project status update.",
    "Conferences and workshops."
]
labels = [0, 1, 0, 1, 0, 1, 0, 1, 0, 0]  # 0: Not Spam, 1: Spam

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(emails, labels, test_size=0.2, random_state=42)

# Vectorize text data using TF-IDF
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# Compute class weights
class_weights = compute_class_weight(class_weight='balanced', classes=np.unique(y_train), y=y_train)

# Train a Multinomial Naïve Bayes Classifier
mnb = MultinomialNB()
mnb.fit(X_train_tfidf, y_train)

# Make predictions on the testing set
y_pred = mnb.predict(X_test_tfidf)

# Evaluate the model
print(classification_report(y_test, y_pred))
print(f"F1-score: {f1_score(y_test, y_pred, average='weighted'):.2f}")

              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       0.00      0.00      0.00         1

    accuracy                           0.50         2
   macro avg       0.25      0.50      0.33         2
weighted avg       0.25      0.50      0.33         2

F1-score: 0.33


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
